mutation UpdateProperty($patch: PatchInput!, $property: UpdatePropertyInput!) {
  updateProperty(patch: $patch, property: $property) {
    version
    properties {
      uid
      name
      description
    }
  }
}