query Viewer($version: String) {
  viewer(version: $version) {
    version
    spaces {
      uid
      name
      description
      traits {
        property {
          uid
        }
        value
        description
      }
    }
    properties {
      uid
      name
      description
    }
    theorems {
      uid
      if
      then
      description
    }
  }
}