query Viewer($version: String) {
  viewer(version: $version) {
    version
    spaces {
      uid
      name
      references { 
        # TODO: these should be fragments
        type
        ref
        name
      }
      description
      traits {
        property {
          uid
        }
        value
        description
        deduced
        references {
          type
          ref
          name
        }
      }
    }
    properties {
      uid
      name
      references {
        type
        ref
        name
      }
      description
    }
    theorems {
      uid
      if
      then
      references {
        type
        ref
        name
      }
      description
    }
  }
}