#!/usr/bin/env ruby

require 'httparty'
require 'json'

ROLLBAR_ACCESS_TOKEN='b3c8ae937ce5402a8b7166c12eae9d86'

revision = `git log -n 1 --pretty=format:"%H"`.strip

version_path = File.expand_path '../../config/version.json', __FILE__
version = JSON.parse File.read version_path
version['app'] = revision
File.write version_path, version.to_json

system 'npm run build'
system 'firebase deploy'

HTTParty.post 'https://api.rollbar.com/api/1/deploy', body: {
  access_token:   ROLLBAR_ACCESS_TOKEN,
  environment:    'production',
  local_username: `whoami`.strip,
  revision:       revision
}
