#!/usr/bin/env ruby

require 'httparty'
require 'json'

ROLLBAR_ACCESS_TOKEN='b3c8ae937ce5402a8b7166c12eae9d86'

revision = `git log -n 1 --pretty=format:"%H"`.strip
data     = JSON.parse(File.read File.expand_path('../../public/db', __FILE__))['version']

File.write File.expand_path('../../public/version.json', __FILE__),
  { app: revision, data: data }.to_json

system 'npm run build'
system 'firebase deploy'

HTTParty.post 'https://api.rollbar.com/api/1/deploy', body: {
  access_token:   ROLLBAR_ACCESS_TOKEN,
  environment:    'production',
  local_username: `whoami`.strip,
  revision:       revision
}
