name: "build-test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cached install
        uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn test --coverage
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
