name: "build-test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cached install
        uses: bahmutov/npm-install@v1.1.0
      - name: Test
        run: yarn test --coverage
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cached install
        uses: bahmutov/npm-install@v1.1.0
      - name: Build
        run: yarn build
        env:
          REACT_APP_BUNDLE_HOST: https://pi-base-bundles.s3.us-east-2.amazonaws.com
          REACT_APP_RELEASE: ${{ github.sha }}
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
